sometimes main can exit 2
  testjson/internal/badmain
  testjson/internal/empty (cached)
  testjson/internal/good.TestPassed (0.00s)
  testjson/internal/good.TestPassedWithLog (0.00s)
  testjson/internal/good.TestPassedWithStdout (0.00s)
  testjson/internal/good.TestSkipped (0.00s)
  testjson/internal/good.TestSkippedWitLog (0.00s)
  testjson/internal/good.TestWithStderr (0.00s)
  testjson/internal/good.TestNestedSuccess/a/sub (0.00s)
  testjson/internal/good.TestNestedSuccess/a (0.00s)
  testjson/internal/good.TestNestedSuccess/b/sub (0.00s)
  testjson/internal/good.TestNestedSuccess/b (0.00s)
  testjson/internal/good.TestNestedSuccess/c/sub (0.00s)
  testjson/internal/good.TestNestedSuccess/c (0.00s)
  testjson/internal/good.TestNestedSuccess/d/sub (0.00s)
  testjson/internal/good.TestNestedSuccess/d (0.00s)
  testjson/internal/good.TestNestedSuccess (0.00s)
  testjson/internal/good.TestParallelTheFirst (0.01s)
  testjson/internal/good.TestParallelTheThird (0.00s)
  testjson/internal/good.TestParallelTheSecond (0.01s)
  testjson/internal/good (cached)
  testjson/internal/parallelfails.TestPassed (0.00s)
  testjson/internal/parallelfails.TestPassedWithLog (0.00s)
  testjson/internal/parallelfails.TestPassedWithStdout (0.00s)
  testjson/internal/parallelfails.TestWithStderr (0.00s)
=== RUN   TestNestedParallelFailures/a
=== PAUSE TestNestedParallelFailures/a
=== CONT  TestNestedParallelFailures/a
    fails_test.go:50: failed sub a
    --- FAIL: TestNestedParallelFailures/a (0.00s)
  testjson/internal/parallelfails.TestNestedParallelFailures/a (0.00s)
=== RUN   TestNestedParallelFailures/d
=== PAUSE TestNestedParallelFailures/d
=== CONT  TestNestedParallelFailures/d
    fails_test.go:50: failed sub d
    --- FAIL: TestNestedParallelFailures/d (0.00s)
  testjson/internal/parallelfails.TestNestedParallelFailures/d (0.00s)
=== RUN   TestNestedParallelFailures/c
=== PAUSE TestNestedParallelFailures/c
=== CONT  TestNestedParallelFailures/c
    fails_test.go:50: failed sub c
    --- FAIL: TestNestedParallelFailures/c (0.00s)
  testjson/internal/parallelfails.TestNestedParallelFailures/c (0.00s)
=== RUN   TestNestedParallelFailures/b
=== PAUSE TestNestedParallelFailures/b
=== CONT  TestNestedParallelFailures/b
    fails_test.go:50: failed sub b
    --- FAIL: TestNestedParallelFailures/b (0.00s)
  testjson/internal/parallelfails.TestNestedParallelFailures/b (0.00s)
=== RUN   TestNestedParallelFailures
--- FAIL: TestNestedParallelFailures (0.00s)
  testjson/internal/parallelfails.TestNestedParallelFailures (0.00s)
=== RUN   TestParallelTheFirst
=== PAUSE TestParallelTheFirst
=== CONT  TestParallelTheFirst
    fails_test.go:29: failed the first
--- FAIL: TestParallelTheFirst (0.01s)
  testjson/internal/parallelfails.TestParallelTheFirst (0.01s)
=== RUN   TestParallelTheThird
=== PAUSE TestParallelTheThird
=== CONT  TestParallelTheThird
    fails_test.go:41: failed the third
--- FAIL: TestParallelTheThird (0.00s)
  testjson/internal/parallelfails.TestParallelTheThird (0.00s)
=== RUN   TestParallelTheSecond
=== PAUSE TestParallelTheSecond
=== CONT  TestParallelTheSecond
    fails_test.go:35: failed the second
--- FAIL: TestParallelTheSecond (0.01s)
  testjson/internal/parallelfails.TestParallelTheSecond (0.01s)
  testjson/internal/parallelfails
  testjson/internal/withfails.TestPassed (0.00s)
  testjson/internal/withfails.TestPassedWithLog (0.00s)
  testjson/internal/withfails.TestPassedWithStdout (0.00s)
  testjson/internal/withfails.TestSkipped (0.00s)
  testjson/internal/withfails.TestSkippedWitLog (0.00s)
=== RUN   TestFailed
    fails_test.go:34: this failed
--- FAIL: TestFailed (0.00s)
  testjson/internal/withfails.TestFailed (0.00s)
  testjson/internal/withfails.TestWithStderr (0.00s)
=== RUN   TestFailedWithStderr
this is stderr
    fails_test.go:43: also failed
--- FAIL: TestFailedWithStderr (0.00s)
  testjson/internal/withfails.TestFailedWithStderr (0.00s)
  testjson/internal/withfails.TestNestedWithFailure/a/sub (0.00s)
  testjson/internal/withfails.TestNestedWithFailure/a (0.00s)
  testjson/internal/withfails.TestNestedWithFailure/b/sub (0.00s)
  testjson/internal/withfails.TestNestedWithFailure/b (0.00s)
=== RUN   TestNestedWithFailure/c
    fails_test.go:65: failed
    --- FAIL: TestNestedWithFailure/c (0.00s)
  testjson/internal/withfails.TestNestedWithFailure/c (0.00s)
  testjson/internal/withfails.TestNestedWithFailure/d/sub (0.00s)
  testjson/internal/withfails.TestNestedWithFailure/d (0.00s)
=== RUN   TestNestedWithFailure
--- FAIL: TestNestedWithFailure (0.00s)
  testjson/internal/withfails.TestNestedWithFailure (0.00s)
  testjson/internal/withfails.TestNestedSuccess/a/sub (0.00s)
  testjson/internal/withfails.TestNestedSuccess/a (0.00s)
  testjson/internal/withfails.TestNestedSuccess/b/sub (0.00s)
  testjson/internal/withfails.TestNestedSuccess/b (0.00s)
  testjson/internal/withfails.TestNestedSuccess/c/sub (0.00s)
  testjson/internal/withfails.TestNestedSuccess/c (0.00s)
  testjson/internal/withfails.TestNestedSuccess/d/sub (0.00s)
  testjson/internal/withfails.TestNestedSuccess/d (0.00s)
  testjson/internal/withfails.TestNestedSuccess (0.00s)
  testjson/internal/withfails.TestTimeout (0.00s)
  testjson/internal/withfails.TestParallelTheFirst (0.01s)
  testjson/internal/withfails.TestParallelTheThird (0.00s)
  testjson/internal/withfails.TestParallelTheSecond (0.01s)
  testjson/internal/withfails
